// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>

// Include the untrusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "helloworld_u.h"

#include <unistd.h>

bool check_simulate_opt(int* argc, const char* argv[])
{
    for (int i = 0; i < *argc; i++)
    {
        if (strcmp(argv[i], "--simulate") == 0)
        {
            fprintf(stdout, "Running in simulation mode\n");
            memmove(&argv[i], &argv[i + 1], (*argc - i) * sizeof(char*));
            (*argc)--;
            return true;
        }
    }
    return false;
}

// This is the function that the enclave will call back into to
// print a message.
void host_helloworld()
{
    fprintf(stdout, "Enclave called into host to print: Hello World!\n");
}

struct file_buffers {
    char *buffers[10];
    int count;
} buffers;

void host_read_file(const char *path, size_t path_size, unsigned char **data, size_t *data_size) {
    printf("host file path: %p:%s\n", path, path);

    FILE *file = fopen(path, "r");
    if (!file) {
        fprintf(stderr, "Failed to open file %s\n", path);
        return;
    }

    fseek(file, 0, SEEK_END);
    size_t size = ftell(file);
    *data_size = size;
    fseek(file, 0, SEEK_SET);

    unsigned char *buffer = (unsigned char *) malloc(size + 1);
    if (!buffer) {
        fprintf(stderr, "Failed to allocate buffer\n");
        fclose(file);
        return;
    }

    buffers.buffers[buffers.count++] = buffer;
    if (fread(buffer, 1, size, file) != size) {
        fprintf(stderr, "Failed to read file\n");
        fclose(file);
        free(buffer);
        return;
    }
    buffer[size] = '\0';

    // buffer = "Hello from host\n";
    // printf("File content: %p:%s\n", buffer, buffer);

    fclose(file);
    *data = buffer;


    // printf("Content: %i %i %i %i %i\n", (int) buffer[0], (int) buffer[1], (int) buffer[2], (int) buffer[3], (int) buffer[4]);

}

int main(int argc, const char* argv[])
{
    buffers.count = 0;
    printf("%s\n", getcwd(NULL, 0));
    oe_result_t result;
    int ret = 1;
    oe_enclave_t* enclave = NULL;

    uint32_t flags = OE_ENCLAVE_FLAG_DEBUG;
    if (check_simulate_opt(&argc, argv))
    {
        flags |= OE_ENCLAVE_FLAG_SIMULATE;
    }

    if (argc != 2)
    {
        fprintf(
            stderr, "Usage: %s enclave_image_path [ --simulate  ]\n", argv[0]);
        goto exit;
    }

    // Create the enclave
    result = oe_create_helloworld_enclave(
        argv[1], OE_ENCLAVE_TYPE_AUTO, flags, NULL, 0, &enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_helloworld_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    // Call into the enclave
    result = enclave_helloworld(enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into enclave_helloworld failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    ret = 0;

exit:
    // Clean up the enclave if we created one
    if (enclave)
        oe_terminate_enclave(enclave);

    return ret;
}
